#!/usr/bin/env bash
# transfers file from local-machine to remote server
total_num_arg=$#
if [[ "$total_num_arg" -lt 3 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    if [ -e "$1" ]; then
        scp -i "$4" "$1" "$3"@"$2":~/
    fi
fi
