#!/usr/bin/env bash
# install nginx web server
sudo apt -y update
sudo apt-get -y install nginx
sudo chown -R "$USER" /var/www
echo 'Hello World' > /var/www/html/index.nginx-debian.html
service nginx start
