#!/usr/bin/env bash
# install nginx web server
apt update
apt -y install nginx
ufw allow 'Nginx HTTP' #  allow all incoming http (port 80) connections
echo 'Hello World!' > /var/www/html/index.html
service nginx start
