#!/usr/bin/env bash
# install Nginx server and redirect to'/redirect_me' page
apt update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/amlaksil permanent;/"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
service nginx start
