#!/usr/bin/env bash
# install Nginx server and redirect to'/redirect_me' page
apt update
apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/amlaksil permanent;/" /etc/nginx/sites-available/default
service nginx start
