#!/usr/bin/env bash
# a script that configures nginx server to have custom 404 page
apt update
apt -y install nginx
echo "Hello World!"> /var/www/html/index.html
echo "Ceci n'est pas une page"> /var/www/html/404.html
sed -i "s/listen 80 default_server;/listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\troot \/var\/www\/html;\n\t}/" /etc/nginx/sites-enabled/default
service nginx start
