#!/usr/bin/env bash
# displays the content of current directory in a list format
# where only the part of the name after the first dash is displayed

for name in *
do
	echo "$name" | cut -d '-' -f 2
done
